version: "3.8"
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

  cloudr:
    container_name: cloudr
    image: cloudr/cloudr:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - temp_data:/data
      - ./cloudr/uploads:/cloudr/uploads
      - ./cloudr/conf.ini:/cloudr/conf.ini
      - ./cloudr/cloudr.db:/cloudr/cloudr.db
      - ./cloudr/avatar:/cloudr/avatar
    depends_on:
      - aria2

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro # third party image, please keep notice what you are doing
    restart: unless-stopped
    environment:
      - RPC_SECRET=your_aria_rpc_token # aria rpc token, customize your own
      - RPC_PORT=6800
    volumes:
      - ./aria2/config:/config
      - temp_data:/data
volumes:
  redis_data:
    driver: local
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
