version: "3.8"
services:
  cloudr:
    container_name: cloudr
    image: ghcr.io/stefandanzl/cloudr:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
#      - /docker/cloudr/conf.ini:/cloudr/conf.ini
#      - /docker/cloudr/cloudr.db:/cloudr/cloudr.db
      - /docker/cloudr/uploads:/cloudr/uploads
      - /docker/cloudr/avatar:/cloudr/avatar
      - /docker/cloudr/mount:/cloudr/mount

