version: '3'

tasks:
  help:
    cmds:
      - echo ""

  yarn_install:
    dir: assets
    cmds:
      - yarn install

  go_mod_tidy:
    cmds:
      - go mod tidy

  setup:
    deps: [yarn_install, go_mod_tidy]

  # Universal tasks
  yarn_build:
    dir: assets
    cmds:
      - yarn build

  create_zip:
    cmds:
      - zip -r assets.zip assets/build

  build_windows:
    cmds:
      - go build -o dev/cloudr.exe
    env:
      GOOS: windows

  go_run:
    cmds:
      - go run .

  firefox:
    dir: "C:/Program Files/Mozilla Firefox"
    cmds:
      - ./firefox.exe --private-window http://localhost:5212

  run-build:
    dir: dev
    cmds:
      - cmd: ./cloudr.exe
        platforms: [windows]
      - cmd: ./cloudr
        platforms: [linux]

  build_linux:
    cmds:
      - go build -o dev/cloudr
    env:
      GOOS: linux

  build_docker:
    cmds:
      - docker build . -t ghcr.io/stefandanzl/cloudr:latest

  push_docker:
    cmds:
      - docker push ghcr.io/stefandanzl/cloudr:latest

  run:
    cmds:
      - cmd: task build_windows
        platforms: [windows]
      - cmd: task build_linux
        platforms: [linux]
      - task: firefox
      - task: run-build
        
  # Local Development tasks
  dev:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: firefox
      - task: go_run

  build:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: build_windows
      - task: run-build

  buildlinux:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: build_linux
      - task: run-build

  docker:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: build_linux
      - task: build_docker
      - task: push_docker

