version: '3'

tasks:

  yarn_install:
    dir: assets
    cmds:
      - yarn install

  go_mod_tidy:
    cmds:
      - go mod tidy

  setup:
    deps: [yarn_install, go_mod_tidy]

  # Universal tasks
  yarn_build:
    dir: assets
    cmds:
      - yarn build

  create_zip:
    cmds:
      - zip -r assets.zip assets/build

  build_windows:
    cmds:
      - go build -o dev/cloudr.exe
    env:
      GOOS: windows

  run_cloudr_windows:
    dir: dev
    cmds:
      - ./cloudr.exe

  run_cloudr_linux:
    dir: dev
    cmds:
      - ./cloudr

  go_run:
    cmds:
      - go run .

  open_firefox:
    cmds:
      - firefox --private-window http://localhost:5212

  # Docker Container tasks
  docker_container:
    cmds:
      - task: yarn_build

    build_linux:
      cmds:
        - go build -o dev/cloudr
      env:
        GOOS: linux

    build_docker:
      cmds:
        - docker build . -t ghcr.io/stefandanzl/cloudr:latest

    push_docker:
      cmds:
        - docker push ghcr.io/stefandanzl/cloudr:latest

  
  # Local Development tasks
  dev:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: go_run


  build:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: build_windows
      - task: run_cloudr

  devlinux:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: build_linux
      - task: run_cloudr

  docker:
    cmds:
      - task: yarn_build
      - task: create_zip
      - task: build_linux
      - task: build_docker
      - task: push_docker

