version: '3'

tasks:
  help:
    cmds:
      - echo ""

  yarn_install:
    dir: assets
    cmds:
      - yarn install

  go_mod_tidy:
    cmds:
      - go mod tidy

  setup:
    deps: [yarn_install, go_mod_tidy]

  # Universal tasks
  yarn_build:
    dir: assets
    cmds:
      - yarn build

  zip:
    cmds:
      - rm -r assets.zip || echo "No assets.zip file"
      - cp -r C:/PROJECTS/PROGRAMMIEREN/Javascript/PSPDFKIT/pspdfkit-lib-2023.5.2 assets/build/pspdfkit-lib/
      - zip -r assets.zip assets/build

  build_windows:
    cmds:
      - go build -o dev/cloudr.exe
    env:
      GOOS: windows

  build_linux:
    cmds:
      - go build -o dev/cloudr
    env:
      GOOS: linux

  build_docker:
    cmds:
      - docker build . -t ghcr.io/stefandanzl/cloudr:latest

  push_docker:
    cmds:
      - docker push ghcr.io/stefandanzl/cloudr:latest

  go_run:
    cmds:
      - go run .

  firefox:
    dir: "C:/Program Files/Mozilla Firefox"
    cmds:
      - ./firefox.exe --private-window http://localhost:5212

  finished:
    cmds:
      - messagebox "Finished task!"

  rclone:
    cmds:
      - "rclone mount devcloudr:/ R: --vfs-cache-mode full --volname Cloudr"





#######

  run_wsl:
    cmds:
      - "'C:/Program Files/Mozilla Firefox/firefox.exe' --private-window http://172.20.6.222:5214"
      - "wsl /mnt/host/c/PROJECTS/GITHUB/cloudr/dev/cloudr"


  run:
    dir: dev
    cmds:
      - task: firefox
      - cmd: ./cloudr.exe
        platforms: [windows]
      - cmd: ./cloudr
        platforms: [linux]

  build-run:
    cmds:
      - cmd: task build_windows
        platforms: [windows]
      - cmd: task build_linux
        platforms: [linux]
      - task: firefox
      - task: run-build
        
  # Local Development tasks
  dev:
    cmds:
      - task: yarn_build
      - task: zip
      - task: firefox
      - task: finished
      - task: go_run

  fulll:
    cmds:
      - cmd: task yarn_build || messagebox "React compilation Error!"
      - task: zip
      - task: build_linux
      - task: finished
      - task: run_wsl

  full:
    cmds:
      - cmd: task yarn_build || messagebox "React compilation Error!"
      - task: zip
      - task: build_windows
      - task: finished
      - task: run

  go:
    cmds:
      - cmd: task build_windows
        platforms: [windows]
      - cmd: task build_linux
        platforms: [linux]
      - task: run

  buildlinux:
    cmds:
      - task: yarn_build
      - task: zip
      - task: build_linux
      - task: run-build

  build-docker:
    cmds:
      - task: yarn_build
      - task: zip
      - task: build_linux
      - task: build_docker
      - task: push_docker
      - task: finished

  docker:
    cmds:
      - task: build_linux
      - task: build_docker
      - task: push_docker
      - task: finished